### PR TITLE
fixes bug related to Arabic text in Tafsir View

### PR DESCRIPTION
**Pull request by moedaaboul**
### Summary
I have raised an issue ticket that describes the error behaviour in https://github.com/quran/quran.com-frontend-next/issues/1910

### Test Plan
This has minimal effect and corrects an error.

### Screenshots

| Before | After |
| ------ | ------ |
| 
before

 | 
after
 |

### CODE REVIEW

**Comment by hazem3500** [comment]
So the `meQuran` font should be deprecated? 🤔

**Comment by moedaaboul** [comment]
Yes, it's not used anywhere in the app, and it is causing all the Quranic text to be corrupted throughout the Ibn Kathir Tafsir translation.  It looks like it was intended to be deleted but was missed out, which can be inferred from this comment: 

```
// TODO: we're not rendering text_uthmani anymore, do we need this font face?
@font-face {
  font-family: "meQuran";
  src: local("me_quran2"),
    url("/fonts/quran/hafs/me_quran/me_quran-2.woff2") format("woff2"),
    url("/fonts/quran/hafs/me_quran/me_quran-2.woff2") format("truetype");
  font-display: swap;
}
```

**Comment by moedaaboul** [comment]
It looks like the font styling is being applied randomly across the pages. You can see from the below that this is the intended styling and now looks fine on the following page:

preview-after

However, the styling is not applied on all the pages consistently as you can see from the below the text is left aligned but is actually meant to be right aligned as it completely misses out both the `arabic` and `uthmani` css rules: 
preview-after-error

I am not sure why there is an inconsistency in the CSS applied to the text, but I suppose it is something to do with how Sass is applied in production though I don't have a clue at this point. **I found this behaviour also on dev whilst debugging locally prior to making any changes, so don't suppose it has to do anything with these changes. Does anyone know whether this will be taken care of once pushed to production?**

**Comment by hazem3500** [comment]
I'm guessing your last point is a separate (yet related) issue? 🤔

Maybe we should write a new issue and tackle it in another PR? 👀

**Comment by moedaaboul** [comment]
Yes, agreed. Let's push these changes then as it looks like Sass rules are applied correctly in production.

**Review by osamasayed — APPROVED** [review]

**Comment by osamasayed** [comment]
@moedaaboul Jazak Allah Kahiran for the fix and your contribution!

**Pull request merged**
