### PR TITLE
Migrate from Jest to Vitest

### PR DESCRIPTION
**Pull request by ahmedriad1**
### Summary
Currently, we use [jest](https://jestjs.io/) for unit tests. However, jest is too slow and requires a lot of dependencies to work properly. So, I propose migrating to [vitest](https://vitest.dev/) - a fast ⚡, light-weight, and better jest-compatible testing framework. Also, the stats after migrating are insane, tests went from `52s` to `4s`.

### Stats

| Before | After |
| ------ | ------ |
| jest | vitest |

### CODE REVIEW

**Comment by shakib2018** [comment]
very very good decision

**Comment by muhajirdev** [comment]
52s to 4s is very significant. 
If there's no gotchas. Looks good to me

**Comment by muhajirdev** [comment]
I found someone is writing this https://dev.to/jjhiggz/comment/1o4a9 . 
```
Cons

it seems to crash a bit more often
````

I don't know how valid the statement is

**Comment by ahmedriad1** [comment]
@muhajirdev 
> I found someone is writing this https://dev.to/jjhiggz/comment/1o4a9 .
> 
> ```
> Cons
> 
> it seems to crash a bit more often
> ```
> 
> I don't know how valid the statement is

The comment was posted on May 2nd. I guess it crashed more often back then. But I think it's production ready now since Vue removed the warning from their [docs](https://vuejs.org/guide/scaling-up/testing.html#unit-testing), and Remix is also using it for their [stacks](https://remix.run/stacks). But, let me know what you think 🤔

**Comment by osamasayed** [comment]
I think it looks promising!! Let's 🛳 it!

**Review by osamasayed — APPROVED** [review]

**Pull request merged**
