### PR TITLE
fix spacing for indopak

### PR DESCRIPTION
**Pull request by naveed-ahmad**
Follow up for #853

### Summary
- Renamed `CharTypeName` to `CharType`
- Removed unused `IndopakWord` component 
- Fixed spacing for `Indopak` words that has waqf sign

P.S Still think we should remove `charType` from words. We now only have `word` and `end` char types now.
Replacing `charType` with boolean `isEnd` attribute makes more sense. And we'll only need this attribute for `end` words. 
 
### Screenshots

| | |
| ------ | ------ |
|Before|before|
|After|after|

### CODE REVIEW

**Comment by osamasayed** [comment]
@naveed-ahmad 

This change seems to break the layout on mobile:

| Before | After |
| ------ | ------ |
|261328983_676548159994438_776048454004367759_n|260366379_1509997792713444_2311557381047434840_n|

**Comment by Ayman24x7** [comment]
> @naveed-ahmad
> 
> This change seems to break the layout on mobile:
> 
> Before	After
> 261328983_676548159994438_776048454004367759_n	260366379_1509997792713444_2311557381047434840_n

@naveed-ahmad 

Assalamu Alaikum,
I'm from Quranwbw.com, I have worked on this WBW Nastaleeq-IndoPak Quran Text and its special Font file.

I have prepared an updated version of the text file (v.9.2.1) and font files (v3.2 -without wakf-lazim margin tag --- & v3.3 -with wakf-lazim margin tag), which can solve this spacing issue. 

I don't know much about coding, but the above solution in the right side picture will work with the new text, because in the new text file all the wa-words (eg. wa-lakum... etc.) are merged with its respective words.

I have also Manually and Digitally verified the whole Quran with King Fahad Glorious Quran Printing Complex Nastaleeq v10 text and I feel confident that it is error free. In'sha'Allah. 

I think @Marwan of Quranwbw.com already sent you the email. If you need the file directly from me then please contact me.

Here is the screenshot from the Ayah-by-Ayah text file (Text file v.9.2.1 and Font file v.3.3)

image

Wakf Lazim Margin tag built into the text which can be toggled by changing the included fonts.

image

Juz Sub divisions and Ruku indicators

image

p.s. There is no need to add juz divisions because it is built into this new text file.

Jazak'Allahu Khair

----

**Comment by naveed-ahmad** [comment]
waAlakim o salam @Ayman24x7 May Allah accept your hard work, this is amazing. JazakAllah kharain for working on this. Yes, br Marwan has already shared the data. Are you on our discord server? If not please join here https://discord.gg/qsj6QCzM I've some questions :)

**Comment by Ayman24x7** [comment]
> waAlakim o salam @Ayman24x7 May Allah accept your hard work, this is amazing. JazakAllah kharain for working on this. Yes, br Marwan has already shared the data. Are you on our discord server? If not please join here https://discord.gg/qsj6QCzM I've some questions :)

Ameen Summa Ameen ! Same to you brother! 
Wa antum fa Jazakumu'llahu khairan, 

Alhamdulillah! 
I joined the discord server and have sent you a friend request. Happy to answer there :)

**Pull request closed without merging**
