### PR TITLE
Changelog follow-up

### LINKED ISSUE #834: Changelog page follow-up tasks
- Have a localized message for Non-English locales that we are showing this in English.
- Have a separate Next.js page for each Notion page
- Add link to the changelog in the beta message + navigation menu
- Change the url to `/product-updates`

### PR DESCRIPTION
**Pull request by osamasayed**
### Summary
Closes #834

### Screenshots

| Before | After |
| ------ | ------ |
|Screen Shot 2021-11-30 at 13 59 52|Screen Shot 2021-11-30 at 14 00 06|
|Screen Shot 2021-11-30 at 13 59 32||
|Screen Shot 2021-11-30 at 14 00 24|Screen Shot 2021-11-30 at 14 00 30|

### CODE REVIEW

**Comment by mmahalwy** [comment]
#### 📝 Changed routes:


| [**/changelog**](https://quran-com-848fwg5v6-qurancom.vercel.app/changelog) | [**/product-updates/\[id\]**](https://quran-com-848fwg5v6-qurancom.vercel.app/product-updates/[id]) |
|:-:|:-:|
|<a href="https://quran-com-848fwg5v6-qurancom.vercel.app/changelog">Screenshot of /changelog</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/PEePpkNmtfbvJ0FYWNRctGtVLhoitFkeUEiAOVZ_hbDJ6MhC5scBxatH0vagw1psFwKQWMRymMXbw3X_FFLgOw.png">(view full size)</a> |<a href="https://quran-com-848fwg5v6-qurancom.vercel.app/product-updates/[id]">Screenshot of /product-updates/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Sgqt1Sjl5tcoflL8YNZR6Q4Yka9UqIkFEGZ0QEITL4IsUDCwy39vkU4pj19i5OSB9mZGU5DXk4bD5bRMDAmmWg.png">(view full size)</a> |



| [**…dates/changelog.module**](https://quran-com-848fwg5v6-qurancom.vercel.app/product-updates/changelog.module) | [**/product-updates**](https://quran-com-848fwg5v6-qurancom.vercel.app/product-updates) |
|:-:|:-:|
|<a href="https://quran-com-848fwg5v6-qurancom.vercel.app/product-updates/changelog.module">Screenshot of /product-updates/changelog.module</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/l-wSryuT_hVqkqd-IFfb3W2YO1pf4wZOO8wV6pE8u-sc_oeezwsAHHOoUi_a2dbaaNBczAftBIZs-Tdrkkjq6w.png">(view full size)</a> |<a href="https://quran-com-848fwg5v6-qurancom.vercel.app/product-updates">Screenshot of /product-updates</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/L11pJA7f9iral56n5IXVpx_brcmjSe7jYhZyaI7Mid0YxN3ipXsYjkwMcQI0Fj113dmDZiwSvb10DSRIJlNfEA.png">(view full size)</a> |







Commit 2fcb7b20c0e3a8a37976a7f6b9b727833420daf0 (https://quran-com-848fwg5v6-qurancom.vercel.app).

**Review by muhajirdev — APPROVED** [review]
aside the font-family and the icon, looks great 👍

**Comment by muhajirdev** [comment]
I think the lighthouse build is missing the token ? https://github.com/quran/quran.com-frontend-next/runs/4364306930?check_suite_focus=true

**Comment by mmahalwy** [comment]
#### 📝 Changed routes:


| [**/changelog**](https://quran-com-r42aztqz7-qurancom.vercel.app/changelog) | [**/product-updates/\[id\]**](https://quran-com-r42aztqz7-qurancom.vercel.app/product-updates/[id]) |
|:-:|:-:|
|<a href="https://quran-com-r42aztqz7-qurancom.vercel.app/changelog">Screenshot of /changelog</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Mo1SP9EMIEJNnuQju-oS9mperPrnYKUn9jotDF8eD9hcFd0aKKg6v3BNAGCDNuRuilVpELrSbS1CRjqXwjeI5w.png">(view full size)</a> |<a href="https://quran-com-r42aztqz7-qurancom.vercel.app/product-updates/[id]">Screenshot of /product-updates/[id]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/CFHWYPlitL-XNPDDo_nLs4yHb3PQML777q8izyrziupxBztetv4BZdm3kSE3NbNCp02D7YuTdyRdbZiXgkhksw.png">(view full size)</a> |



| [**…dates/changelog.module**](https://quran-com-r42aztqz7-qurancom.vercel.app/product-updates/changelog.module) | [**/product-updates**](https://quran-com-r42aztqz7-qurancom.vercel.app/product-updates) |
|:-:|:-:|
|<a href="https://quran-com-r42aztqz7-qurancom.vercel.app/product-updates/changelog.module">Screenshot of /product-updates/changelog.module</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/QZHIDgkv8S_Xj_LNXAwoy3bP4FnMTqQg5RfdmUQmsTP7fODPSWdRaox_-Tk2CVy80_KdMligjkSg6U1Dnxx0Ng.png">(view full size)</a> |<a href="https://quran-com-r42aztqz7-qurancom.vercel.app/product-updates">Screenshot of /product-updates</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ZXRkPoCDLm7Ug_WvljbBl0kJU1onZVhGjJoapjusxepzS1W2JaZ-uN150JXUtoZeq7MRmOJKzXa2i0vd344crw.png">(view full size)</a> |







Commit 07a84ded6987bf2e5562fc4d93018e43b48d603c (https://quran-com-r42aztqz7-qurancom.vercel.app).

**Pull request merged**
