### PR TITLE
global navbar merge

### PR DESCRIPTION
**Pull request by soghammed**
Global Navbar added issue#11

### CODE REVIEW

**Comment by mmahalwy** [comment]
#### 📝Changed routes:


| [**/**](https://quran-com-frontend-next-git-fork-soghammed-master.qurancom.now.sh/) |
|:-:|
|<a href="https://quran-com-frontend-next-git-fork-soghammed-master.qurancom.now.sh/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/6_mqC8lQs9OfK4M6jI7OkEKHewE_.png">(view full size)</a> |







Commit 4a1598f88c18215c483b09ee718db3f8448f93d1 (https://quran-com-frontend-next-git-fork-soghammed-master.qurancom.now.sh).

**Comment by soghammed** [comment]
Prefer fragment shorthand over React.Fragment
And button type attribute

Is that it?

**Comment by soghammed** [comment]
what's needed for the deployment to work?

**Comment by soghammed** [comment]
?..

**Comment by mmahalwy** [comment]
@soghammed let me take a look

**Pull request closed without merging**
