### PR TITLE
Set up next-translate

### PR DESCRIPTION
**Pull request by tifa2UP**
### Summary
Addresses #35  

Integrates [next-translate](https://github.com/vinissimus/next-translate) into the Quran.com repo. We now have URLs for different supported locales, for example: 

```
/5/2 (English)
/ar/5/2 (Arabic)
/en/5/2 -> /5/2 (English)
```

Added support for English and Arabic, Need to create 2 follow-up PRs: 

1. Refactor all the strings to `useTranslation()` 
2. Hide generated files from the Github PR preview

### Test Plan

Tested the existing URLs by appending `/ar/` at the beginning of the path. The url works for Arabic, and returns `404` for unsupported languages. 

Confirmed that `yarn build`, `yarn start`, and `yarn dev` are all working.

### CODE REVIEW

**Comment by mmahalwy** [comment]
#### 📝Changed routes:


| [**/\[chapterId\]**](https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/[chapterId]) | [**/about**](https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/about) |
|:-:|:-:|
|<a href="https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/[chapterId]">Screenshot of /[chapterId]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/ZrNSRLDUQpKlJQ5LzwaZH1_38vU_.png">(view full size)</a> |<a href="https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/about">Screenshot of /about</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/IzJ3Lpu372SowdA0AjO4zS9E3ds_.png">(view full size)</a> |



| [**/ar/\[chapterId\]**](https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/ar/[chapterId]) | [**/ar/about**](https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/ar/about) |
|:-:|:-:|
|<a href="https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/ar/[chapterId]">Screenshot of /ar/[chapterId]</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/YWGDkRzMEUs6icCp2TT_E_CfCf8_.png">(view full size)</a> |<a href="https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/ar/about">Screenshot of /ar/about</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/87ItfpdvIu0PqG7MIR9QSg5_Nso_.png">(view full size)</a> |



| [**/ar**](https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/ar) | [**/**](https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/) |
|:-:|:-:|
|<a href="https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/ar">Screenshot of /ar</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/0tpS9AVmwNc26F3Jt9noz5qwhEM_.png">(view full size)</a> |<a href="https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh/">Screenshot of /</a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/SW9l5YvZS_tY2RAIUJ_x_mGRUpE_.png">(view full size)</a> |







Commit b178735be49be880d153126e8aca8b87fac96206 (https://quran-com-frontend-next-git-integrate-next-translate.qurancom.now.sh).

**Comment by mmahalwy** [comment]
Also, can we copy this content? https://github.com/quran/quran.com-frontend/blob/master/src/locale/en.ts

**Comment by mmahalwy** [comment]
This is an interesting VS Code extension :) https://marketplace.visualstudio.com/items?itemName=funkyremi.vscode-google-translate

**Comment by tifa2UP** [comment]
Nice. 

> This is super awesome. Just one thing, is it possible to prevent anyone from making changes to the pages/ directory?

Added the auto-generated `pages/` under `.gitignore`

> Also, can we copy this content? quran/quran.com-frontend:src/locale/en.ts@master

We are going to have the strings for each page under a separate json file, like: 

```
.
├── ca
│   ├── common.json
│   └── home.json
├── en
│   ├── common.json
│   └── home.json
└── es
    ├── common.json
    └── home.json
```

Happy to put them all under `common.json` now but we'll have to refactor it down the line. 

> This is an interesting VS Code extension :) marketplace.visualstudio.com/items?itemName=funkyremi.vscode-google-translate

Sweet, I'll check it out!

**Pull request merged**
