### PR TITLE
fix: prevent (tafsir)content modal from closing when scrolling via scrollbar

### LINKED ISSUE #1149: [bug]: Bug in ContentModal
### Is there an existing issue for this?

- [X] There is no exsiting issue for this bug

### Describe the bug

When I try to use scrollbar in `ContentModal` it crashes

here is a preview:

preview

I guess it's because the modal is inside `Dialog.Overlay`, which is also responsible for scrolling

### Relevant log output

_No response_

### Steps to reproduce

Open tafsirs modal and try to use the scrollbar

### Environment (please complete the following information) and Add any other context about this bug

OS: Windows 11
Browser: Chrome
Version: 97.0.4692.99

### Environment

Production(beta.quran.com)

### PR DESCRIPTION
**Pull request by yj7o5**
### Summary
This PR closes #1149 where by when trying to scroll through the tafsir, the content modal would close out.

### Test Plan
1. Open a browser and go to https://beta.quran.com/1
2. Click on the menu options and select "Tafsir"
3. Try to scroll through the details

### Screenshots

| Before | After |
| ------ | ------ |
| before | after |

### CODE REVIEW

**Comment by yj7o5** [comment]
@osamasayed whenever you get chance. JazakAllah

**Comment by osamasayed** [comment]
> Salaam, @osamasayed whenever you get chance. JazakAllah

Wa'likum Alsalam @yj7o5 Jazak Allah Kahiran for you contribution. I am not why but I am still experiencing the issue of the Modal closing out when you scroll.

**Comment by yj7o5** [comment]
hmm interesting, on my local it seems to be working fine but not on the preview site. Will investigate!

**Comment by osamasayed** [comment]
> hmm interesting, on my local it seems to be working fine but not on the preview site. Will investigate, Insha Allah.

This seems to be a Radix [issue](https://github.com/radix-ui/primitives/issues/1280). Hopefully once they resolve it, we can update the package version and this will be resolved automatically inshAllah. Jazak Allah Khairan for your effort.

**Comment by osamasayed** [comment]
Alsalamu Alikum @yj7o5, I believe I found a fix to the issue. Would be great if you can test it and confirm that it's fixed. JazakAllah Khairan.

**Review by osamasayed — APPROVED** [review]

**Pull request merged**
