### PR TITLE
add tests for array util functions

### PR DESCRIPTION
**Pull request by MedoAngel**
### Summary
These are some tests for the first function in array util functions this is just a draft, when maintainers approve of it and discuss it further will be applied to all functions of the file

### Screenshots

| Before | After |
| ------ | ------ |
| [image here] | [image here] |

### CODE REVIEW

**Comment by osamasayed** [comment]
Salam @MedoAngel Jazak Allahu Khairan for your help. PR looks good. Feel free to add tests to the rest of the `array` util file. Also if it's something you are interested in, we need help with [setting up E2E tests](https://github.com/quran/quran.com-frontend-next/issues/962) using [Playwright](https://playwright.dev/).

**Comment by MedoAngel** [comment]
> Salam @MedoAngel Jazak Allahu Khairan for your help. PR looks good. Feel free to add tests to the rest of the `array` util file. Also if it's something you are interested in, we need help with [setting up E2E tests](https://github.com/quran/quran.com-frontend-next/issues/962) using [Playwright](https://playwright.dev/).

Yes of course absolutely, I'm not familiar with Playwright but shouldn't be that hard to figure out, Inshallah will look into it soon

**Comment by MedoAngel** [comment]
@osamasayed All done with adding the tests for array util functions

**Comment by osamasayed** [comment]
> @osamasayed All done with adding the tests for array util functions

Jazak Allahu Khairan. PR is merged!

**Pull request merged**
